package com.javaweb.model;
// Generated Oct 17, 2017 2:11:23 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArticleLike generated by hbm2java
 */
@Entity
@Table(name = "article_like", catalog = "duan2_webapplication_tintucgame")
public class ArticleLike implements java.io.Serializable {

	private Integer articleLikeId;
	private Article article;
	private Users users;
	private Date createDate;
	private String description;

	public ArticleLike() {
	}

	public ArticleLike(Article article, Users users, Date createDate) {
		this.article = article;
		this.users = users;
		this.createDate = createDate;
	}

	public ArticleLike(Article article, Users users, Date createDate, String description) {
		this.article = article;
		this.users = users;
		this.createDate = createDate;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "article_like_id", unique = true, nullable = false)
	public Integer getArticleLikeId() {
		return this.articleLikeId;
	}

	public void setArticleLikeId(Integer articleLikeId) {
		this.articleLikeId = articleLikeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "article_id", nullable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
