package com.javaweb.model;
// Generated Oct 15, 2017 3:20:39 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommentLikeForum generated by hbm2java
 */
@Entity
@Table(name = "comment_like_forum", catalog = "duan2_webapplication_tintucgame")
public class CommentLikeForum implements java.io.Serializable {

	private int commentLikeForumId;
	private CommentForum commentForum;
	private Users users;
	private Date createDate;
	private String description;

	public CommentLikeForum() {
	}

	public CommentLikeForum(int commentLikeForumId, CommentForum commentForum, Users users, Date createDate) {
		this.commentLikeForumId = commentLikeForumId;
		this.commentForum = commentForum;
		this.users = users;
		this.createDate = createDate;
	}

	public CommentLikeForum(int commentLikeForumId, CommentForum commentForum, Users users, Date createDate,
			String description) {
		this.commentLikeForumId = commentLikeForumId;
		this.commentForum = commentForum;
		this.users = users;
		this.createDate = createDate;
		this.description = description;
	}

	@Id

	@Column(name = "comment_like_forum_id", unique = true, nullable = false)
	public int getCommentLikeForumId() {
		return this.commentLikeForumId;
	}

	public void setCommentLikeForumId(int commentLikeForumId) {
		this.commentLikeForumId = commentLikeForumId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comment_forum_id", nullable = false)
	public CommentForum getCommentForum() {
		return this.commentForum;
	}

	public void setCommentForum(CommentForum commentForum) {
		this.commentForum = commentForum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
