package com.javaweb.model;
// Generated Nov 5, 2017 10:08:55 AM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommentLikeForum generated by hbm2java
 */
@Entity
@Table(name = "comment_like_forum", catalog = "duan2_webapplication_tintucgame")
public class CommentLikeForum implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8278033654349577910L;
	private Integer commentLikeForumId;
	private CommentForum commentForum;
	private Users users;
	private Date createDate;
	private String description;

	public CommentLikeForum() {
	}

	public CommentLikeForum(CommentForum commentForum, Users users, Date createDate) {
		this.commentForum = commentForum;
		this.users = users;
		this.createDate = createDate;
	}

	public CommentLikeForum(CommentForum commentForum, Users users, Date createDate, String description) {
		this.commentForum = commentForum;
		this.users = users;
		this.createDate = createDate;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "comment_like_forum_id", unique = true, nullable = false)
	public Integer getCommentLikeForumId() {
		return this.commentLikeForumId;
	}

	public void setCommentLikeForumId(Integer commentLikeForumId) {
		this.commentLikeForumId = commentLikeForumId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comment_forum_id", nullable = false)
	public CommentForum getCommentForum() {
		return this.commentForum;
	}

	public void setCommentForum(CommentForum commentForum) {
		this.commentForum = commentForum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
