package com.javaweb.model;
// Generated Oct 18, 2017 12:22:20 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommentForum generated by hbm2java
 */
@Entity
@Table(name = "comment_forum", catalog = "duan2_webapplication_tintucgame")
public class CommentForum implements java.io.Serializable {

	private Integer commentForumId;
	private ArticleForum articleForum;
	private Users users;
	private Integer subCommentForumId;
	private String content;
	private Date createdDate;
	private Date modifiedDate;
	private String status;
	private String ip;
	private String description;
	private Set<CommentLikeForum> commentLikeForums = new HashSet<CommentLikeForum>(0);

	public CommentForum() {
	}

	public CommentForum(ArticleForum articleForum, Users users, String content, Date createdDate, String status) {
		this.articleForum = articleForum;
		this.users = users;
		this.content = content;
		this.createdDate = createdDate;
		this.status = status;
	}

	public CommentForum(ArticleForum articleForum, Users users, Integer subCommentForumId, String content,
			Date createdDate, Date modifiedDate, String status, String ip, String description,
			Set<CommentLikeForum> commentLikeForums) {
		this.articleForum = articleForum;
		this.users = users;
		this.subCommentForumId = subCommentForumId;
		this.content = content;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.status = status;
		this.ip = ip;
		this.description = description;
		this.commentLikeForums = commentLikeForums;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "comment_forum_id", unique = true, nullable = false)
	public Integer getCommentForumId() {
		return this.commentForumId;
	}

	public void setCommentForumId(Integer commentForumId) {
		this.commentForumId = commentForumId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "article_forum_id", nullable = false)
	public ArticleForum getArticleForum() {
		return this.articleForum;
	}

	public void setArticleForum(ArticleForum articleForum) {
		this.articleForum = articleForum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "sub_comment_forum_id")
	public Integer getSubCommentForumId() {
		return this.subCommentForumId;
	}

	public void setSubCommentForumId(Integer subCommentForumId) {
		this.subCommentForumId = subCommentForumId;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ip", length = 50)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commentForum")
	public Set<CommentLikeForum> getCommentLikeForums() {
		return this.commentLikeForums;
	}

	public void setCommentLikeForums(Set<CommentLikeForum> commentLikeForums) {
		this.commentLikeForums = commentLikeForums;
	}

}
