package com.javaweb.model;
// Generated Nov 5, 2017 10:08:55 AM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GameReviews generated by hbm2java
 */
@Entity
@Table(name = "game_reviews", catalog = "duan2_webapplication_tintucgame")
public class GameReviews implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5252426848349560943L;
	private Integer gameReviewId;
	private Games games;
	private Users users;
	private Date createDate;
	private double review;
	private String status;
	private String description;

	public GameReviews() {
	}

	public GameReviews(Games games, Users users, Date createDate, double review, String status) {
		this.games = games;
		this.users = users;
		this.createDate = createDate;
		this.review = review;
		this.status = status;
	}

	public GameReviews(Games games, Users users, Date createDate, double review, String status, String description) {
		this.games = games;
		this.users = users;
		this.createDate = createDate;
		this.review = review;
		this.status = status;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "game_review_id", unique = true, nullable = false)
	public Integer getGameReviewId() {
		return this.gameReviewId;
	}

	public void setGameReviewId(Integer gameReviewId) {
		this.gameReviewId = gameReviewId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "game_id", nullable = false)
	public Games getGames() {
		return this.games;
	}

	public void setGames(Games games) {
		this.games = games;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "review", nullable = false, precision = 22, scale = 0)
	public double getReview() {
		return this.review;
	}

	public void setReview(double review) {
		this.review = review;
	}

	@Column(name = "status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
