package com.javaweb.model;
// Generated Oct 17, 2017 2:11:23 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Games generated by hbm2java
 */
@Entity
@Table(name = "games", catalog = "duan2_webapplication_tintucgame", uniqueConstraints = {
		@UniqueConstraint(columnNames = "name"), @UniqueConstraint(columnNames = "slug") })
public class Games implements java.io.Serializable {

	private Integer gameId;
	private GameCategory gameCategory;
	private String name;
	private String slug;
	private String developers;
	private String publishers;
	private String writers;
	private String composers;
	private String engine;
	private String platforms;
	private String release;
	private String info;
	private String status;
	private String description;
	private Set<GameReviews> gameReviewses = new HashSet<GameReviews>(0);

	public Games() {
	}

	public Games(GameCategory gameCategory, String name, String slug, String publishers, String release,
			String status) {
		this.gameCategory = gameCategory;
		this.name = name;
		this.slug = slug;
		this.publishers = publishers;
		this.release = release;
		this.status = status;
	}

	public Games(GameCategory gameCategory, String name, String slug, String developers, String publishers,
			String writers, String composers, String engine, String platforms, String release, String info,
			String status, String description, Set<GameReviews> gameReviewses) {
		this.gameCategory = gameCategory;
		this.name = name;
		this.slug = slug;
		this.developers = developers;
		this.publishers = publishers;
		this.writers = writers;
		this.composers = composers;
		this.engine = engine;
		this.platforms = platforms;
		this.release = release;
		this.info = info;
		this.status = status;
		this.description = description;
		this.gameReviewses = gameReviewses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "game_id", unique = true, nullable = false)
	public Integer getGameId() {
		return this.gameId;
	}

	public void setGameId(Integer gameId) {
		this.gameId = gameId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "game_category_id", nullable = false)
	public GameCategory getGameCategory() {
		return this.gameCategory;
	}

	public void setGameCategory(GameCategory gameCategory) {
		this.gameCategory = gameCategory;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "slug", unique = true, nullable = false)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "developers", length = 1000)
	public String getDevelopers() {
		return this.developers;
	}

	public void setDevelopers(String developers) {
		this.developers = developers;
	}

	@Column(name = "publishers", nullable = false, length = 1000)
	public String getPublishers() {
		return this.publishers;
	}

	public void setPublishers(String publishers) {
		this.publishers = publishers;
	}

	@Column(name = "writers", length = 1000)
	public String getWriters() {
		return this.writers;
	}

	public void setWriters(String writers) {
		this.writers = writers;
	}

	@Column(name = "composers", length = 1000)
	public String getComposers() {
		return this.composers;
	}

	public void setComposers(String composers) {
		this.composers = composers;
	}

	@Column(name = "engine", length = 1000)
	public String getEngine() {
		return this.engine;
	}

	public void setEngine(String engine) {
		this.engine = engine;
	}

	@Column(name = "platforms", length = 1000)
	public String getPlatforms() {
		return this.platforms;
	}

	public void setPlatforms(String platforms) {
		this.platforms = platforms;
	}

	@Column(name = "release", nullable = false, length = 1000)
	public String getRelease() {
		return this.release;
	}

	public void setRelease(String release) {
		this.release = release;
	}

	@Column(name = "info", length = 1000)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "games")
	public Set<GameReviews> getGameReviewses() {
		return this.gameReviewses;
	}

	public void setGameReviewses(Set<GameReviews> gameReviewses) {
		this.gameReviewses = gameReviewses;
	}

}
