package com.javaweb.model;
// Generated Oct 15, 2017 3:20:39 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pages generated by hbm2java
 */
@Entity
@Table(name = "pages", catalog = "duan2_webapplication_tintucgame", uniqueConstraints = @UniqueConstraint(columnNames = "slug"))
public class Pages implements java.io.Serializable {

	private Integer pageId;
	private String name;
	private String slug;
	private String content;
	private byte status;
	private String description;

	public Pages() {
	}

	public Pages(String name, String slug, String content, byte status) {
		this.name = name;
		this.slug = slug;
		this.content = content;
		this.status = status;
	}

	public Pages(String name, String slug, String content, byte status, String description) {
		this.name = name;
		this.slug = slug;
		this.content = content;
		this.status = status;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "page_id", unique = true, nullable = false)
	public Integer getPageId() {
		return this.pageId;
	}

	public void setPageId(Integer pageId) {
		this.pageId = pageId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "slug", unique = true, nullable = false)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
