package com.javaweb.model;
// Generated Oct 18, 2017 12:22:20 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", catalog = "duan2_webapplication_tintucgame", uniqueConstraints = {
		@UniqueConstraint(columnNames = "name"), @UniqueConstraint(columnNames = "slug") })
public class Tags implements java.io.Serializable {

	private Integer tagsId;
	private String name;
	private String slug;
	private String description;
	private Set<Article> articles = new HashSet<Article>(0);

	public Tags() {
	}

	public Tags(String name, String slug) {
		this.name = name;
		this.slug = slug;
	}

	public Tags(String name, String slug, String description, Set<Article> articles) {
		this.name = name;
		this.slug = slug;
		this.description = description;
		this.articles = articles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tags_id", unique = true, nullable = false)
	public Integer getTagsId() {
		return this.tagsId;
	}

	public void setTagsId(Integer tagsId) {
		this.tagsId = tagsId;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "slug", unique = true, nullable = false)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tagses")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
